### ISSUE TITLE
The links to high quality transit corridors require a login.

### ISSUE THREAD

**Issue by aickin** [BayAreaMetro/Data-And-Visualization-Projects#1]
Hi there! I've been making [a map](https://www.transitrichhousing.org/) over the last week or so to document the potential impact of SB 827, and I found out about your amazing datasets of Major Transit Stops and High Quality Transit Corridors. Thanks so much for them!

However, when I tried to download any of the four HQTC files, the GIS server requires that I log in, and it won't let me register. Since this doesn't happen with MTS file, I'm guessing it's an error. Could you make the HQTC files public possibly? Thanks!

**Comment by tbdv** [comment]
hey @aickin sorry i didn't reply to this earlier, we were working quickly on rapidly changing 827 amendments. since 827 is dead now, i guess its moot. 

i later had time (on weekends) to make some of the process more formalized as a fork of the gtfsr package: https://github.com/r-transit/tidytransit

did you ever end up publishing your code? i really enjoyed the cartography. would be curious to see how you approached the problem analytically. its a tough one!
